// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nofcngway/feed-service/internal/storage/pgstorage"
	mock "github.com/stretchr/testify/mock"
)

// NewFeedService creates a new instance of FeedService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeedService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeedService {
	mock := &FeedService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FeedService is an autogenerated mock type for the FeedService type
type FeedService struct {
	mock.Mock
}

type FeedService_Expecter struct {
	mock *mock.Mock
}

func (_m *FeedService) EXPECT() *FeedService_Expecter {
	return &FeedService_Expecter{mock: &_m.Mock}
}

// GetFeed provides a mock function for the type FeedService
func (_mock *FeedService) GetFeed(ctx context.Context, userID int64, limit int32, offset int32) ([]pgstorage.FeedItem, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFeed")
	}

	var r0 []pgstorage.FeedItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, int32) ([]pgstorage.FeedItem, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, int32) []pgstorage.FeedItem); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgstorage.FeedItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FeedService_GetFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeed'
type FeedService_GetFeed_Call struct {
	*mock.Call
}

// GetFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int32
//   - offset int32
func (_e *FeedService_Expecter) GetFeed(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *FeedService_GetFeed_Call {
	return &FeedService_GetFeed_Call{Call: _e.mock.On("GetFeed", ctx, userID, limit, offset)}
}

func (_c *FeedService_GetFeed_Call) Run(run func(ctx context.Context, userID int64, limit int32, offset int32)) *FeedService_GetFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FeedService_GetFeed_Call) Return(feedItems []pgstorage.FeedItem, err error) *FeedService_GetFeed_Call {
	_c.Call.Return(feedItems, err)
	return _c
}

func (_c *FeedService_GetFeed_Call) RunAndReturn(run func(ctx context.Context, userID int64, limit int32, offset int32) ([]pgstorage.FeedItem, error)) *FeedService_GetFeed_Call {
	_c.Call.Return(run)
	return _c
}
