// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type AuthService
func (_mock *AuthService) CreatePost(ctx context.Context, token string, postID int64) error {
	ret := _mock.Called(ctx, token, postID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, token, postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type AuthService_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - postID int64
func (_e *AuthService_Expecter) CreatePost(ctx interface{}, token interface{}, postID interface{}) *AuthService_CreatePost_Call {
	return &AuthService_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, token, postID)}
}

func (_c *AuthService_CreatePost_Call) Run(run func(ctx context.Context, token string, postID int64)) *AuthService_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_CreatePost_Call) Return(err error) *AuthService_CreatePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_CreatePost_Call) RunAndReturn(run func(ctx context.Context, token string, postID int64) error) *AuthService_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// Follow provides a mock function for the type AuthService
func (_mock *AuthService) Follow(ctx context.Context, token string, targetUserID int64) error {
	ret := _mock.Called(ctx, token, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, token, targetUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type AuthService_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - targetUserID int64
func (_e *AuthService_Expecter) Follow(ctx interface{}, token interface{}, targetUserID interface{}) *AuthService_Follow_Call {
	return &AuthService_Follow_Call{Call: _e.mock.On("Follow", ctx, token, targetUserID)}
}

func (_c *AuthService_Follow_Call) Run(run func(ctx context.Context, token string, targetUserID int64)) *AuthService_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Follow_Call) Return(err error) *AuthService_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Follow_Call) RunAndReturn(run func(ctx context.Context, token string, targetUserID int64) error) *AuthService_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// Like provides a mock function for the type AuthService
func (_mock *AuthService) Like(ctx context.Context, token string, postID int64) error {
	ret := _mock.Called(ctx, token, postID)

	if len(ret) == 0 {
		panic("no return value specified for Like")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, token, postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Like_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Like'
type AuthService_Like_Call struct {
	*mock.Call
}

// Like is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - postID int64
func (_e *AuthService_Expecter) Like(ctx interface{}, token interface{}, postID interface{}) *AuthService_Like_Call {
	return &AuthService_Like_Call{Call: _e.mock.On("Like", ctx, token, postID)}
}

func (_c *AuthService_Like_Call) Run(run func(ctx context.Context, token string, postID int64)) *AuthService_Like_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Like_Call) Return(err error) *AuthService_Like_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Like_Call) RunAndReturn(run func(ctx context.Context, token string, postID int64) error) *AuthService_Like_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthService
func (_mock *AuthService) Login(ctx context.Context, username string, password string) (string, int64, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, int64, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(token string, userID int64, err error) *AuthService_Login_Call {
	_c.Call.Return(token, userID, err)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, int64, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthService
func (_mock *AuthService) Logout(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthService_Expecter) Logout(ctx interface{}, token interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, token string)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(err error) *AuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, token string) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthService
func (_mock *AuthService) Register(ctx context.Context, username string, password string) (string, int64, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, int64, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int64); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthService_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, username string, password string)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(token string, userID int64, err error) *AuthService_Register_Call {
	_c.Call.Return(token, userID, err)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (string, int64, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
