// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/nofcngway/auth-action-service/internal/sessions"
	"github.com/nofcngway/auth-action-service/internal/storage/pgstorage"
	mock "github.com/stretchr/testify/mock"
)

// NewUserStorage creates a new instance of UserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStorage {
	mock := &UserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserStorage is an autogenerated mock type for the UserStorage type
type UserStorage struct {
	mock.Mock
}

type UserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStorage) EXPECT() *UserStorage_Expecter {
	return &UserStorage_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserStorage
func (_mock *UserStorage) CreateUser(ctx context.Context, username string, passwordHash string) (int64, error) {
	ret := _mock.Called(ctx, username, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, username, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, username, passwordHash)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - passwordHash string
func (_e *UserStorage_Expecter) CreateUser(ctx interface{}, username interface{}, passwordHash interface{}) *UserStorage_CreateUser_Call {
	return &UserStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, passwordHash)}
}

func (_c *UserStorage_CreateUser_Call) Run(run func(ctx context.Context, username string, passwordHash string)) *UserStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserStorage_CreateUser_Call) Return(n int64, err error) *UserStorage_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, username string, passwordHash string) (int64, error)) *UserStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type UserStorage
func (_mock *UserStorage) GetUserByUsername(ctx context.Context, username string) (*pgstorage.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *pgstorage.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*pgstorage.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *pgstorage.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgstorage.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStorage_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type UserStorage_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserStorage_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *UserStorage_GetUserByUsername_Call {
	return &UserStorage_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *UserStorage_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *UserStorage_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStorage_GetUserByUsername_Call) Return(user *pgstorage.User, err error) *UserStorage_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserStorage_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*pgstorage.User, error)) *UserStorage_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function for the type UserStorage
func (_mock *UserStorage) UserExists(ctx context.Context, id int64) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserStorage_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type UserStorage_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserStorage_Expecter) UserExists(ctx interface{}, id interface{}) *UserStorage_UserExists_Call {
	return &UserStorage_UserExists_Call{Call: _e.mock.On("UserExists", ctx, id)}
}

func (_c *UserStorage_UserExists_Call) Run(run func(ctx context.Context, id int64)) *UserStorage_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserStorage_UserExists_Call) Return(b bool, err error) *UserStorage_UserExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserStorage_UserExists_Call) RunAndReturn(run func(ctx context.Context, id int64) (bool, error)) *UserStorage_UserExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionStore creates a new instance of SessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStore {
	mock := &SessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionStore is an autogenerated mock type for the SessionStore type
type SessionStore struct {
	mock.Mock
}

type SessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionStore) EXPECT() *SessionStore_Expecter {
	return &SessionStore_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type SessionStore
func (_mock *SessionStore) Del(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStore_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type SessionStore_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionStore_Expecter) Del(ctx interface{}, token interface{}) *SessionStore_Del_Call {
	return &SessionStore_Del_Call{Call: _e.mock.On("Del", ctx, token)}
}

func (_c *SessionStore_Del_Call) Run(run func(ctx context.Context, token string)) *SessionStore_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStore_Del_Call) Return(err error) *SessionStore_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStore_Del_Call) RunAndReturn(run func(ctx context.Context, token string) error) *SessionStore_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionStore
func (_mock *SessionStore) Get(ctx context.Context, token string) (*sessions.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sessions.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sessions.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sessions.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionStore_Expecter) Get(ctx interface{}, token interface{}) *SessionStore_Get_Call {
	return &SessionStore_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *SessionStore_Get_Call) Run(run func(ctx context.Context, token string)) *SessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionStore_Get_Call) Return(session *sessions.Session, err error) *SessionStore_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionStore_Get_Call) RunAndReturn(run func(ctx context.Context, token string) (*sessions.Session, error)) *SessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type SessionStore
func (_mock *SessionStore) Set(ctx context.Context, token string, session sessions.Session, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, sessions.Session, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, session, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type SessionStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - session sessions.Session
//   - ttl time.Duration
func (_e *SessionStore_Expecter) Set(ctx interface{}, token interface{}, session interface{}, ttl interface{}) *SessionStore_Set_Call {
	return &SessionStore_Set_Call{Call: _e.mock.On("Set", ctx, token, session, ttl)}
}

func (_c *SessionStore_Set_Call) Run(run func(ctx context.Context, token string, session sessions.Session, ttl time.Duration)) *SessionStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 sessions.Session
		if args[2] != nil {
			arg2 = args[2].(sessions.Session)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *SessionStore_Set_Call) Return(err error) *SessionStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionStore_Set_Call) RunAndReturn(run func(ctx context.Context, token string, session sessions.Session, ttl time.Duration) error) *SessionStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Producer
func (_mock *Producer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Producer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Producer_Expecter) Close() *Producer_Close_Call {
	return &Producer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Producer_Close_Call) Run(run func()) *Producer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Producer_Close_Call) Return(err error) *Producer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Close_Call) RunAndReturn(run func() error) *Producer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type Producer
func (_mock *Producer) Publish(ctx context.Context, userID int64, action string, targetID int64) error {
	ret := _mock.Called(ctx, userID, action, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) error); ok {
		r0 = returnFunc(ctx, userID, action, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Producer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - action string
//   - targetID int64
func (_e *Producer_Expecter) Publish(ctx interface{}, userID interface{}, action interface{}, targetID interface{}) *Producer_Publish_Call {
	return &Producer_Publish_Call{Call: _e.mock.On("Publish", ctx, userID, action, targetID)}
}

func (_c *Producer_Publish_Call) Run(run func(ctx context.Context, userID int64, action string, targetID int64)) *Producer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Producer_Publish_Call) Return(err error) *Producer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Publish_Call) RunAndReturn(run func(ctx context.Context, userID int64, action string, targetID int64) error) *Producer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
