// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/nofcngway/feed-service/internal/storage/pgstorage"
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetFeed provides a mock function for the type Storage
func (_mock *Storage) GetFeed(ctx context.Context, userID int64, limit int32, offset int32) ([]pgstorage.FeedItem, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFeed")
	}

	var r0 []pgstorage.FeedItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, int32) ([]pgstorage.FeedItem, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int32, int32) []pgstorage.FeedItem); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgstorage.FeedItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int32, int32) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetFeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeed'
type Storage_GetFeed_Call struct {
	*mock.Call
}

// GetFeed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int32
//   - offset int32
func (_e *Storage_Expecter) GetFeed(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *Storage_GetFeed_Call {
	return &Storage_GetFeed_Call{Call: _e.mock.On("GetFeed", ctx, userID, limit, offset)}
}

func (_c *Storage_GetFeed_Call) Run(run func(ctx context.Context, userID int64, limit int32, offset int32)) *Storage_GetFeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Storage_GetFeed_Call) Return(feedItems []pgstorage.FeedItem, err error) *Storage_GetFeed_Call {
	_c.Call.Return(feedItems, err)
	return _c
}

func (_c *Storage_GetFeed_Call) RunAndReturn(run func(ctx context.Context, userID int64, limit int32, offset int32) ([]pgstorage.FeedItem, error)) *Storage_GetFeed_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFeedItem provides a mock function for the type Storage
func (_mock *Storage) InsertFeedItem(ctx context.Context, userID int64, actorID int64, action string, targetID int64, createdAt time.Time) error {
	ret := _mock.Called(ctx, userID, actorID, action, targetID, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertFeedItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, int64, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, actorID, action, targetID, createdAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Storage_InsertFeedItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFeedItem'
type Storage_InsertFeedItem_Call struct {
	*mock.Call
}

// InsertFeedItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - actorID int64
//   - action string
//   - targetID int64
//   - createdAt time.Time
func (_e *Storage_Expecter) InsertFeedItem(ctx interface{}, userID interface{}, actorID interface{}, action interface{}, targetID interface{}, createdAt interface{}) *Storage_InsertFeedItem_Call {
	return &Storage_InsertFeedItem_Call{Call: _e.mock.On("InsertFeedItem", ctx, userID, actorID, action, targetID, createdAt)}
}

func (_c *Storage_InsertFeedItem_Call) Run(run func(ctx context.Context, userID int64, actorID int64, action string, targetID int64, createdAt time.Time)) *Storage_InsertFeedItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Storage_InsertFeedItem_Call) Return(err error) *Storage_InsertFeedItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Storage_InsertFeedItem_Call) RunAndReturn(run func(ctx context.Context, userID int64, actorID int64, action string, targetID int64, createdAt time.Time) error) *Storage_InsertFeedItem_Call {
	_c.Call.Return(run)
	return _c
}
