// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: feed_api/feed.proto

package feed_api

import (
	models "github.com/nofcngway/feed-service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_feed_api_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_api_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFeedRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFeedResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*models.FeedItemModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_feed_api_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_api_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_api_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedResponse) GetItems() []*models.FeedItemModel {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_feed_api_feed_proto protoreflect.FileDescriptor

const file_feed_api_feed_proto_rawDesc = "" +
	"\n" +
	"\x13feed_api/feed.proto\x12\x0ffeed.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17models/feed_model.proto\"W\n" +
	"\x0eGetFeedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"F\n" +
	"\x0fGetFeedResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.feed.models.v1.FeedItemModelR\x05items2j\n" +
	"\vFeedService\x12[\n" +
	"\aGetFeed\x12\x1f.feed.service.v1.GetFeedRequest\x1a .feed.service.v1.GetFeedResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/feedBAZ?github.com/nofcngway/feed-service/internal/pb/feed_api;feed_apib\x06proto3"

var (
	file_feed_api_feed_proto_rawDescOnce sync.Once
	file_feed_api_feed_proto_rawDescData []byte
)

func file_feed_api_feed_proto_rawDescGZIP() []byte {
	file_feed_api_feed_proto_rawDescOnce.Do(func() {
		file_feed_api_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_api_feed_proto_rawDesc), len(file_feed_api_feed_proto_rawDesc)))
	})
	return file_feed_api_feed_proto_rawDescData
}

var file_feed_api_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feed_api_feed_proto_goTypes = []any{
	(*GetFeedRequest)(nil),       // 0: feed.service.v1.GetFeedRequest
	(*GetFeedResponse)(nil),      // 1: feed.service.v1.GetFeedResponse
	(*models.FeedItemModel)(nil), // 2: feed.models.v1.FeedItemModel
}
var file_feed_api_feed_proto_depIdxs = []int32{
	2, // 0: feed.service.v1.GetFeedResponse.items:type_name -> feed.models.v1.FeedItemModel
	0, // 1: feed.service.v1.FeedService.GetFeed:input_type -> feed.service.v1.GetFeedRequest
	1, // 2: feed.service.v1.FeedService.GetFeed:output_type -> feed.service.v1.GetFeedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feed_api_feed_proto_init() }
func file_feed_api_feed_proto_init() {
	if File_feed_api_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_api_feed_proto_rawDesc), len(file_feed_api_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_api_feed_proto_goTypes,
		DependencyIndexes: file_feed_api_feed_proto_depIdxs,
		MessageInfos:      file_feed_api_feed_proto_msgTypes,
	}.Build()
	File_feed_api_feed_proto = out.File
	file_feed_api_feed_proto_goTypes = nil
	file_feed_api_feed_proto_depIdxs = nil
}
