// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: auth_action_api/auth_action.proto

package auth_action_api

import (
	models "github.com/nofcngway/auth-action-service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_action_api_auth_action_proto protoreflect.FileDescriptor

const file_auth_action_api_auth_action_proto_rawDesc = "" +
	"\n" +
	"!auth_action_api/auth_action.proto\x12\x16auth_action.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17models/auth_model.proto2\xbf\x04\n" +
	"\x11AuthActionService\x12[\n" +
	"\bRegister\x12\x1b.auth.models.v1.AuthRequest\x1a\x1c.auth.models.v1.AuthResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/register\x12U\n" +
	"\x05Login\x12\x1b.auth.models.v1.AuthRequest\x1a\x1c.auth.models.v1.AuthResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12P\n" +
	"\x06Logout\x12\x15.auth.models.v1.Empty\x1a\x1e.auth.models.v1.ActionResponse\"\x0f\x82\xd3\xe4\x93\x02\t\"\a/logout\x12\\\n" +
	"\x04Like\x12\x1b.auth.models.v1.LikeRequest\x1a\x1e.auth.models.v1.ActionResponse\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0f/like/{post_id}\x12b\n" +
	"\x06Follow\x12\x1d.auth.models.v1.FollowRequest\x1a\x1e.auth.models.v1.ActionResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/follow/{user_id}\x12b\n" +
	"\n" +
	"CreatePost\x12!.auth.models.v1.CreatePostRequest\x1a\x1e.auth.models.v1.ActionResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/postsBFZDgithub.com/nofcngway/auth-action-service/internal/pb/auth_action_apib\x06proto3"

var file_auth_action_api_auth_action_proto_goTypes = []any{
	(*models.AuthRequest)(nil),       // 0: auth.models.v1.AuthRequest
	(*models.Empty)(nil),             // 1: auth.models.v1.Empty
	(*models.LikeRequest)(nil),       // 2: auth.models.v1.LikeRequest
	(*models.FollowRequest)(nil),     // 3: auth.models.v1.FollowRequest
	(*models.CreatePostRequest)(nil), // 4: auth.models.v1.CreatePostRequest
	(*models.AuthResponse)(nil),      // 5: auth.models.v1.AuthResponse
	(*models.ActionResponse)(nil),    // 6: auth.models.v1.ActionResponse
}
var file_auth_action_api_auth_action_proto_depIdxs = []int32{
	0, // 0: auth_action.service.v1.AuthActionService.Register:input_type -> auth.models.v1.AuthRequest
	0, // 1: auth_action.service.v1.AuthActionService.Login:input_type -> auth.models.v1.AuthRequest
	1, // 2: auth_action.service.v1.AuthActionService.Logout:input_type -> auth.models.v1.Empty
	2, // 3: auth_action.service.v1.AuthActionService.Like:input_type -> auth.models.v1.LikeRequest
	3, // 4: auth_action.service.v1.AuthActionService.Follow:input_type -> auth.models.v1.FollowRequest
	4, // 5: auth_action.service.v1.AuthActionService.CreatePost:input_type -> auth.models.v1.CreatePostRequest
	5, // 6: auth_action.service.v1.AuthActionService.Register:output_type -> auth.models.v1.AuthResponse
	5, // 7: auth_action.service.v1.AuthActionService.Login:output_type -> auth.models.v1.AuthResponse
	6, // 8: auth_action.service.v1.AuthActionService.Logout:output_type -> auth.models.v1.ActionResponse
	6, // 9: auth_action.service.v1.AuthActionService.Like:output_type -> auth.models.v1.ActionResponse
	6, // 10: auth_action.service.v1.AuthActionService.Follow:output_type -> auth.models.v1.ActionResponse
	6, // 11: auth_action.service.v1.AuthActionService.CreatePost:output_type -> auth.models.v1.ActionResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_action_api_auth_action_proto_init() }
func file_auth_action_api_auth_action_proto_init() {
	if File_auth_action_api_auth_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_action_api_auth_action_proto_rawDesc), len(file_auth_action_api_auth_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_action_api_auth_action_proto_goTypes,
		DependencyIndexes: file_auth_action_api_auth_action_proto_depIdxs,
	}.Build()
	File_auth_action_api_auth_action_proto = out.File
	file_auth_action_api_auth_action_proto_goTypes = nil
	file_auth_action_api_auth_action_proto_depIdxs = nil
}
