// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: auth_action_api/auth_action.proto

package auth_action_api

import (
	context "context"
	models "github.com/nofcngway/auth-action-service/internal/pb/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthActionService_Register_FullMethodName   = "/auth_action.service.v1.AuthActionService/Register"
	AuthActionService_Login_FullMethodName      = "/auth_action.service.v1.AuthActionService/Login"
	AuthActionService_Logout_FullMethodName     = "/auth_action.service.v1.AuthActionService/Logout"
	AuthActionService_Like_FullMethodName       = "/auth_action.service.v1.AuthActionService/Like"
	AuthActionService_Follow_FullMethodName     = "/auth_action.service.v1.AuthActionService/Follow"
	AuthActionService_CreatePost_FullMethodName = "/auth_action.service.v1.AuthActionService/CreatePost"
)

// AuthActionServiceClient is the client API for AuthActionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthActionService предоставляет HTTP/gRPC методы для регистрации/логина и пользовательских действий.
type AuthActionServiceClient interface {
	// Register регистрирует нового пользователя и создаёт сессию (возвращает token и user_id).
	Register(ctx context.Context, in *models.AuthRequest, opts ...grpc.CallOption) (*models.AuthResponse, error)
	// Login выполняет вход пользователя и создаёт/обновляет сессию (возвращает token и user_id).
	Login(ctx context.Context, in *models.AuthRequest, opts ...grpc.CallOption) (*models.AuthResponse, error)
	// Logout удаляет текущую сессию по токену из заголовка Authorization.
	Logout(ctx context.Context, in *models.Empty, opts ...grpc.CallOption) (*models.ActionResponse, error)
	// Like публикует событие лайка (требуется Authorization: Bearer <token>).
	Like(ctx context.Context, in *models.LikeRequest, opts ...grpc.CallOption) (*models.ActionResponse, error)
	// Follow публикует событие подписки (требуется Authorization: Bearer <token>).
	Follow(ctx context.Context, in *models.FollowRequest, opts ...grpc.CallOption) (*models.ActionResponse, error)
	// CreatePost публикует событие создания поста (требуется Authorization: Bearer <token>).
	CreatePost(ctx context.Context, in *models.CreatePostRequest, opts ...grpc.CallOption) (*models.ActionResponse, error)
}

type authActionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthActionServiceClient(cc grpc.ClientConnInterface) AuthActionServiceClient {
	return &authActionServiceClient{cc}
}

func (c *authActionServiceClient) Register(ctx context.Context, in *models.AuthRequest, opts ...grpc.CallOption) (*models.AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.AuthResponse)
	err := c.cc.Invoke(ctx, AuthActionService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authActionServiceClient) Login(ctx context.Context, in *models.AuthRequest, opts ...grpc.CallOption) (*models.AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.AuthResponse)
	err := c.cc.Invoke(ctx, AuthActionService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authActionServiceClient) Logout(ctx context.Context, in *models.Empty, opts ...grpc.CallOption) (*models.ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ActionResponse)
	err := c.cc.Invoke(ctx, AuthActionService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authActionServiceClient) Like(ctx context.Context, in *models.LikeRequest, opts ...grpc.CallOption) (*models.ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ActionResponse)
	err := c.cc.Invoke(ctx, AuthActionService_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authActionServiceClient) Follow(ctx context.Context, in *models.FollowRequest, opts ...grpc.CallOption) (*models.ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ActionResponse)
	err := c.cc.Invoke(ctx, AuthActionService_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authActionServiceClient) CreatePost(ctx context.Context, in *models.CreatePostRequest, opts ...grpc.CallOption) (*models.ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.ActionResponse)
	err := c.cc.Invoke(ctx, AuthActionService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthActionServiceServer is the server API for AuthActionService service.
// All implementations must embed UnimplementedAuthActionServiceServer
// for forward compatibility.
//
// AuthActionService предоставляет HTTP/gRPC методы для регистрации/логина и пользовательских действий.
type AuthActionServiceServer interface {
	// Register регистрирует нового пользователя и создаёт сессию (возвращает token и user_id).
	Register(context.Context, *models.AuthRequest) (*models.AuthResponse, error)
	// Login выполняет вход пользователя и создаёт/обновляет сессию (возвращает token и user_id).
	Login(context.Context, *models.AuthRequest) (*models.AuthResponse, error)
	// Logout удаляет текущую сессию по токену из заголовка Authorization.
	Logout(context.Context, *models.Empty) (*models.ActionResponse, error)
	// Like публикует событие лайка (требуется Authorization: Bearer <token>).
	Like(context.Context, *models.LikeRequest) (*models.ActionResponse, error)
	// Follow публикует событие подписки (требуется Authorization: Bearer <token>).
	Follow(context.Context, *models.FollowRequest) (*models.ActionResponse, error)
	// CreatePost публикует событие создания поста (требуется Authorization: Bearer <token>).
	CreatePost(context.Context, *models.CreatePostRequest) (*models.ActionResponse, error)
	mustEmbedUnimplementedAuthActionServiceServer()
}

// UnimplementedAuthActionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthActionServiceServer struct{}

func (UnimplementedAuthActionServiceServer) Register(context.Context, *models.AuthRequest) (*models.AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthActionServiceServer) Login(context.Context, *models.AuthRequest) (*models.AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthActionServiceServer) Logout(context.Context, *models.Empty) (*models.ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthActionServiceServer) Like(context.Context, *models.LikeRequest) (*models.ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedAuthActionServiceServer) Follow(context.Context, *models.FollowRequest) (*models.ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedAuthActionServiceServer) CreatePost(context.Context, *models.CreatePostRequest) (*models.ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedAuthActionServiceServer) mustEmbedUnimplementedAuthActionServiceServer() {}
func (UnimplementedAuthActionServiceServer) testEmbeddedByValue()                           {}

// UnsafeAuthActionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthActionServiceServer will
// result in compilation errors.
type UnsafeAuthActionServiceServer interface {
	mustEmbedUnimplementedAuthActionServiceServer()
}

func RegisterAuthActionServiceServer(s grpc.ServiceRegistrar, srv AuthActionServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthActionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthActionService_ServiceDesc, srv)
}

func _AuthActionService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).Register(ctx, req.(*models.AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthActionService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).Login(ctx, req.(*models.AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthActionService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).Logout(ctx, req.(*models.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthActionService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).Like(ctx, req.(*models.LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthActionService_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).Follow(ctx, req.(*models.FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthActionService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthActionServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthActionService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthActionServiceServer).CreatePost(ctx, req.(*models.CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthActionService_ServiceDesc is the grpc.ServiceDesc for AuthActionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthActionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_action.service.v1.AuthActionService",
	HandlerType: (*AuthActionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthActionService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthActionService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthActionService_Logout_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _AuthActionService_Like_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _AuthActionService_Follow_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _AuthActionService_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_action_api/auth_action.proto",
}
