// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: models/feed_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedItemModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       int64                  `protobuf:"varint,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemModel) Reset() {
	*x = FeedItemModel{}
	mi := &file_models_feed_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemModel) ProtoMessage() {}

func (x *FeedItemModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_feed_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemModel.ProtoReflect.Descriptor instead.
func (*FeedItemModel) Descriptor() ([]byte, []int) {
	return file_models_feed_model_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItemModel) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *FeedItemModel) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedItemModel) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *FeedItemModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_models_feed_model_proto protoreflect.FileDescriptor

const file_models_feed_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/feed_model.proto\x12\x0efeed.models.v1\"~\n" +
	"\rFeedItemModel\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\x03R\aactorId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB6Z4github.com/nofcngway/feed-service/internal/pb/modelsb\x06proto3"

var (
	file_models_feed_model_proto_rawDescOnce sync.Once
	file_models_feed_model_proto_rawDescData []byte
)

func file_models_feed_model_proto_rawDescGZIP() []byte {
	file_models_feed_model_proto_rawDescOnce.Do(func() {
		file_models_feed_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_feed_model_proto_rawDesc), len(file_models_feed_model_proto_rawDesc)))
	})
	return file_models_feed_model_proto_rawDescData
}

var file_models_feed_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_feed_model_proto_goTypes = []any{
	(*FeedItemModel)(nil), // 0: feed.models.v1.FeedItemModel
}
var file_models_feed_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_feed_model_proto_init() }
func file_models_feed_model_proto_init() {
	if File_models_feed_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_feed_model_proto_rawDesc), len(file_models_feed_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_feed_model_proto_goTypes,
		DependencyIndexes: file_models_feed_model_proto_depIdxs,
		MessageInfos:      file_models_feed_model_proto_msgTypes,
	}.Build()
	File_models_feed_model_proto = out.File
	file_models_feed_model_proto_goTypes = nil
	file_models_feed_model_proto_depIdxs = nil
}
